# Generated by Django 3.1.3 on 2020-12-03 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_1', models.CharField(blank=True, max_length=200, verbose_name='News title 1')),
                ('news_post_image', models.ImageField(blank=True, upload_to='news/images', verbose_name='News post image')),
                ('news_post_title', models.CharField(blank=True, max_length=200, verbose_name='News post title')),
                ('slug', models.SlugField(max_length=120, unique=True, verbose_name='News slug')),
                ('new_post_description', models.TextField(blank=True, verbose_name='News description')),
                ('news_post_date', models.DateTimeField(auto_now=True, verbose_name='News post date')),
            ],
            options={
                'verbose_name': 'new',
                'verbose_name_plural': 'news',
                'ordering': ('title_1',),
                'index_together': {('id', 'slug')},
            },
        ),
    ]
