# Generated by Django 3.1.3 on 2020-12-03 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='author',
            field=models.CharField(blank=True, max_length=50, verbose_name='Author'),
        ),
        migrations.AddField(
            model_name='news',
            name='description_1',
            field=models.TextField(blank=True, verbose_name='Description 1'),
        ),
        migrations.AddField(
            model_name='news',
            name='description_2',
            field=models.TextField(blank=True, verbose_name='Description 2 '),
        ),
        migrations.AddField(
            model_name='news',
            name='description_3',
            field=models.TextField(blank=True, verbose_name='Description 3'),
        ),
        migrations.AddField(
            model_name='news',
            name='intro',
            field=models.TextField(blank=True, verbose_name='News intro'),
        ),
        migrations.AddField(
            model_name='news',
            name='news_image_1',
            field=models.ImageField(blank=True, upload_to='news/images', verbose_name='Image field'),
        ),
        migrations.AddField(
            model_name='news',
            name='news_image_2',
            field=models.ImageField(blank=True, upload_to='news/images', verbose_name='Image field 2'),
        ),
        migrations.AddField(
            model_name='news',
            name='published_on',
            field=models.CharField(blank=True, max_length=50, verbose_name='published'),
        ),
        migrations.AddField(
            model_name='news',
            name='testimonial',
            field=models.TextField(blank=True, verbose_name='News testimonial'),
        ),
        migrations.AddField(
            model_name='news',
            name='testimonial_author',
            field=models.CharField(blank=True, max_length=50, verbose_name='Title testimonial'),
        ),
        migrations.AddField(
            model_name='news',
            name='title_2',
            field=models.CharField(blank=True, max_length=200, verbose_name='News title 2'),
        ),
        migrations.AddField(
            model_name='news',
            name='title_3',
            field=models.CharField(blank=True, max_length=50, verbose_name='Title 3'),
        ),
        migrations.AddField(
            model_name='news',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='news/videos'),
        ),
    ]
