# Generated by Django 3.1.3 on 2020-12-03 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20201203_1708'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='title_4',
            field=models.CharField(blank=True, max_length=50, verbose_name='Title 4'),
        ),
    ]
