# Generated by Django 3.1.3 on 2020-12-03 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_news_title_5'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ('news_post_title',), 'verbose_name': 'new', 'verbose_name_plural': 'news'},
        ),
        migrations.RemoveField(
            model_name='news',
            name='author',
        ),
        migrations.RemoveField(
            model_name='news',
            name='description_1',
        ),
        migrations.RemoveField(
            model_name='news',
            name='description_2',
        ),
        migrations.RemoveField(
            model_name='news',
            name='description_3',
        ),
        migrations.RemoveField(
            model_name='news',
            name='intro',
        ),
        migrations.RemoveField(
            model_name='news',
            name='new_post_description',
        ),
        migrations.RemoveField(
            model_name='news',
            name='news_image_1',
        ),
        migrations.RemoveField(
            model_name='news',
            name='news_image_2',
        ),
        migrations.RemoveField(
            model_name='news',
            name='published_on',
        ),
        migrations.RemoveField(
            model_name='news',
            name='testimonial',
        ),
        migrations.RemoveField(
            model_name='news',
            name='testimonial_author',
        ),
        migrations.RemoveField(
            model_name='news',
            name='title_1',
        ),
        migrations.RemoveField(
            model_name='news',
            name='title_2',
        ),
        migrations.RemoveField(
            model_name='news',
            name='title_3',
        ),
        migrations.RemoveField(
            model_name='news',
            name='title_4',
        ),
        migrations.RemoveField(
            model_name='news',
            name='title_5',
        ),
        migrations.RemoveField(
            model_name='news',
            name='video_file',
        ),
        migrations.AddField(
            model_name='news',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='news',
            name='slug',
            field=models.SlugField(verbose_name='Slug'),
        ),
    ]
