# Generated by Django 3.1.3 on 2020-12-03 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, verbose_name='Service name')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='Service slug')),
                ('service_description', models.TextField(blank=True, verbose_name='Service description')),
                ('service_image', models.ImageField(upload_to='services/images', verbose_name='Service image')),
            ],
            options={
                'verbose_name': 'service',
                'verbose_name_plural': 'services',
                'ordering': ('name',),
                'index_together': {('id', 'slug')},
            },
        ),
    ]
