# Generated by Django 3.1.3 on 2020-12-03 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, verbose_name='Service title')),
                ('description', models.TextField(blank=True, verbose_name='Service description')),
                ('image', models.ImageField(blank=True, upload_to='service/image', verbose_name='Service image')),
            ],
        ),
        migrations.AddField(
            model_name='service',
            name='title',
            field=models.CharField(blank=True, max_length=200, verbose_name='Title in Detail'),
        ),
        migrations.AddField(
            model_name='service',
            name='services',
            field=models.ManyToManyField(blank=True, to='service.ServiceList', verbose_name='Choose service'),
        ),
    ]
