# Generated by Django 3.1.3 on 2020-12-05 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=18, verbose_name='Phone Company')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email Company')),
                ('address', models.CharField(blank=True, max_length=200, verbose_name='Company address')),
                ('logo', models.ImageField(blank=True, upload_to='contact/images', verbose_name='Company logo')),
                ('image', models.ImageField(blank=True, upload_to='contact/images', verbose_name='Company image')),
            ],
            options={
                'verbose_name': 'Contact',
                'verbose_name_plural': 'Contacts',
            },
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading1', models.CharField(blank=True, max_length=200, verbose_name='Slider Heading 1')),
                ('heading2', models.CharField(blank=True, max_length=200, verbose_name='Slider Heading 2')),
                ('desc', models.CharField(blank=True, max_length=200, verbose_name='Opisanie')),
                ('photo', models.ImageField(blank=True, upload_to='slider/images', verbose_name='Slider photo')),
                ('video', models.CharField(blank=True, max_length=200, verbose_name='Slider Background Video')),
            ],
            options={
                'verbose_name': 'Slide',
                'verbose_name_plural': 'Slides',
            },
        ),
    ]
