# Generated by Django 3.1.3 on 2020-12-05 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_contact_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact',
            new_name='Contacts',
        ),
    ]
