# Generated by Django 3.1 on 2020-12-15 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_contactformus'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='photo_map',
            field=models.ImageField(blank=True, upload_to='slider/images', verbose_name='Slider photo map'),
        ),
    ]
