# Generated by Django 3.1.3 on 2020-12-03 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Colors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash', models.CharField(blank=True, max_length=10, verbose_name='Ranglar')),
            ],
        ),
        migrations.CreateModel(
            name='ImageCollection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, verbose_name='Picture name')),
                ('image', models.ImageField(blank=True, upload_to='brand/image_col', verbose_name='Image collection')),
            ],
        ),
        migrations.CreateModel(
            name='ImageGallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, verbose_name='Picture name')),
                ('gallery', models.ImageField(blank=True, upload_to='brand/gallery', verbose_name='Brand gallery')),
            ],
        ),
        migrations.CreateModel(
            name='Photography',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, verbose_name='photography name')),
                ('slug', models.SlugField(blank=True, max_length=200, verbose_name='photography slug')),
                ('year', models.DateField(blank=True, null=True, verbose_name='photo year')),
                ('photo_image', models.ImageField(blank=True, upload_to='photo/images', verbose_name='photography image')),
                ('photo_description', models.TextField(blank=True)),
                ('photo_title', models.CharField(blank=True, max_length=200, verbose_name='photo title')),
            ],
            options={
                'verbose_name': 'photography',
                'verbose_name_plural': 'photographies',
                'ordering': ('name',),
                'index_together': {('id', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='Webdesign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, verbose_name='Web type')),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('web_title', models.CharField(blank=True, max_length=200, verbose_name='Web title')),
                ('year', models.DateField(blank=True, null=True, verbose_name='web year')),
                ('web_image', models.ImageField(blank=True, upload_to='web/images', verbose_name='Web Image front')),
                ('web_image_pc', models.ImageField(blank=True, upload_to='web/images', verbose_name='Detail Image PC')),
                ('web_image_mobile', models.ImageField(blank=True, upload_to='web/images', verbose_name='Detail Image MOBILE')),
                ('client', models.CharField(blank=True, max_length=150, verbose_name='Client Name')),
                ('service', models.CharField(blank=True, max_length=150, verbose_name='Service Name')),
                ('web_description', models.TextField(blank=True, verbose_name='About project')),
                ('web_image_full', models.ImageField(blank=True, upload_to='web/images', verbose_name='Web_Full_Image')),
                ('typography1', models.CharField(blank=True, max_length=50, verbose_name='Typography Primary')),
                ('typography2', models.CharField(blank=True, max_length=50, verbose_name='Typography Primary')),
                ('colors_pattern', models.ManyToManyField(blank=True, to='portfolio.Colors', verbose_name='Colors')),
            ],
            options={
                'verbose_name': 'web',
                'verbose_name_plural': 'webs',
                'ordering': ('name',),
                'index_together': {('id', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=120, verbose_name='Brand name')),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('brand_title', models.CharField(blank=True, max_length=200, verbose_name='Brand title')),
                ('year', models.DateField(blank=True, null=True, verbose_name='Brand year')),
                ('brand_image', models.ImageField(blank=True, upload_to='brand/images', verbose_name='Brand image')),
                ('brand_description', models.TextField(blank=True)),
                ('client', models.CharField(blank=True, max_length=150, verbose_name='Client Name')),
                ('service', models.CharField(blank=True, max_length=150, verbose_name='Service Name')),
                ('idea', models.TextField(blank=True, verbose_name='brand idea')),
                ('approach', models.TextField(blank=True, verbose_name='brand approach')),
                ('gallery', models.ManyToManyField(blank=True, to='portfolio.ImageGallery', verbose_name='brand image gallery')),
                ('image_col', models.ManyToManyField(blank=True, to='portfolio.ImageCollection', verbose_name='Brand Image collection')),
            ],
            options={
                'verbose_name': 'brand',
                'verbose_name_plural': 'brands',
                'ordering': ('name',),
                'index_together': {('id', 'slug')},
            },
        ),
    ]
