# Generated by Django 3.1.3 on 2020-12-03 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_remove_brand_idea'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, verbose_name='Photo Portfolio')),
                ('image', models.ImageField(blank=True, upload_to='portfolio/photo', verbose_name='Photography Portfolio')),
            ],
        ),
        migrations.RemoveField(
            model_name='brand',
            name='approach',
        ),
        migrations.AddField(
            model_name='photography',
            name='client',
            field=models.CharField(blank=True, max_length=50, verbose_name='Client'),
        ),
        migrations.AddField(
            model_name='photography',
            name='service',
            field=models.CharField(blank=True, max_length=50, verbose_name='Service'),
        ),
        migrations.AddField(
            model_name='photography',
            name='pictures',
            field=models.ManyToManyField(blank=True, to='portfolio.PhotoImages', verbose_name='Portfolio Photo'),
        ),
    ]
