# Generated by Django 3.1.3 on 2020-12-03 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_auto_20201203_1217'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photoimages',
            old_name='image',
            new_name='pictures',
        ),
    ]
