# Generated by Django 3.1.3 on 2020-12-14 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_auto_20201203_1225'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='brand_image_cover',
            field=models.ImageField(blank=True, upload_to='brand/images', verbose_name='Brand Cover'),
        ),
    ]
